%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.4.1

-ifndef(messages).
-define(messages, true).

-define(messages_gpb_version, "4.4.1").

-ifndef('LOGIN_PB_H').
-define('LOGIN_PB_H', true).
-record('Login',
        {username = []          :: iolist() | undefined, % = 1
         password = []          :: iolist() | undefined % = 2
        }).
-endif.

-ifndef('LOGINRESPONSE_PB_H').
-define('LOGINRESPONSE_PB_H', true).
-record('LoginResponse',
        {result = false         :: boolean() | 0 | 1 | undefined, % = 1
         message = []           :: iolist() | undefined % = 2
        }).
-endif.

-ifndef('LOGOUT_PB_H').
-define('LOGOUT_PB_H', true).
-record('Logout',
        {username = []          :: iolist() | undefined % = 1
        }).
-endif.

-ifndef('LOGOUTRESPONSE_PB_H').
-define('LOGOUTRESPONSE_PB_H', true).
-record('LogoutResponse',
        {result = false         :: boolean() | 0 | 1 | undefined, % = 1
         message = []           :: iolist() | undefined % = 2
        }).
-endif.

-endif.
