%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.4.1

-ifndef(auth).
-define(auth, true).

-define(auth_gpb_version, "4.4.1").

-ifndef('REQUEST_PB_H').
-define('REQUEST_PB_H', true).
-record('Request',
        {type = []              :: iolist() | undefined, % = 1
         username = []          :: iolist() | undefined, % = 2
         password = []          :: iolist() | undefined % = 3
        }).
-endif.

-ifndef('REPLY_PB_H').
-define('REPLY_PB_H', true).
-record('Reply',
        {result = false         :: boolean() | 0 | 1 | undefined, % = 1
         message = []           :: iolist() | undefined % = 2
        }).
-endif.

-endif.
