/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package psd.client;

/**
 * @author diogo
 */
public class DiretorioPage extends javax.swing.JFrame {

    /**
     * Creates new form InvestorPage
     */
    public DiretorioPage() {
        initComponents();
    }

    private void refresh() {
        Messages.AuctionList alist = ErlangBridge.getInstance().auctionList();
        Messages.FixedList flist = ErlangBridge.getInstance().fixedList();
        int count = alist.getEntryCount();
        this.auctionsListArea.setText("");
        for (int i = 0; i < count; ++i) {
            Messages.AuctionEntry entry = alist.getEntry(i);
            this.auctionsListArea.append(entry.getCompany() 
                    + '\t'
                    + entry.getAmount()
                    + '\t' 
                    + entry.getInterest() 
                    + '\n');
        }
        count = flist.getEntryCount();
        this.fixedListArea.removeAll();
        for (int i = 0; i < count; ++i) {
            Messages.FixedEntry entry = flist.getEntry(i);
            this.fixedListArea.append(entry.getCompany() 
                    + '\t'
                    + entry.getAmount()
                    + '\t' 
                    + entry.getInterest() 
                    + '\n');
        }
    } 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        refresh = new javax.swing.JButton();
        company = new javax.swing.JTextField();
        getButton = new javax.swing.JButton();
        fixedListPane = new javax.swing.JScrollPane();
        fixedListArea = new javax.swing.JTextArea();
        auctionsListPane = new javax.swing.JScrollPane();
        auctionsListArea = new javax.swing.JTextArea();
        menu = new javax.swing.JMenuBar();
        file = new javax.swing.JMenu();
        close = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel1.setText("Companies");

        jLabel2.setText("Details");

        refresh.setText("Refresh");
        refresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshMouseClicked(evt);
            }
        });

        company.setText("Company");
        company.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                companyFocusGained(evt);
            }
        });
        company.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companyActionPerformed(evt);
            }
        });

        getButton.setText("Get");
        getButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                getButtonMouseClicked(evt);
            }
        });

        fixedListArea.setColumns(20);
        fixedListArea.setRows(5);
        fixedListPane.setViewportView(fixedListArea);

        auctionsListArea.setColumns(20);
        auctionsListArea.setRows(5);
        auctionsListPane.setViewportView(auctionsListArea);

        file.setText("File");

        close.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        close.setText("Close");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        file.add(close);

        menu.add(file);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(auctionsListPane, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(372, 409, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(company, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(getButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(fixedListPane)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fixedListPane)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(company, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(getButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(auctionsListPane, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(refresh)))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeActionPerformed

    private void companyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_companyActionPerformed

    private void refreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshMouseClicked
        // TODO add your handling code here:
        final String company = this.companyFieldAuction.getText();
        final int amount = Integer.parseInt(this.amountFieldAuction.getText());
        final double interest = Double.parseDouble(this.interestFieldAuction.getText());
        final boolean success = ErlangBridge.getInstance().bidAuction(this.username, company, amount, interest);
        if (success) {
            this.auctionsNotiArea.append("Successfull bid in company "
                    + company
                    + " with amount "
                    + amount
                    + " at interest "
                    + interest + "\n"
            );
        } else {
            this.auctionsNotiArea.append("Error bidding in company "
                    + company
                    + " with amount "
                    + amount
                    + " at interest "
                    + interest + "\n"
            );
        }
    }//GEN-LAST:event_refreshMouseClicked

    private void getButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_getButtonMouseClicked
        // TODO add your handling code here:
        final String company = this.companyFieldFixed.getText();
        final int amount = Integer.parseInt(this.company.getText());
        final boolean success = ErlangBridge.getInstance().subscribeFixed(this.username, company, amount);
        if (success) {
            this.fixedNotiArea.append("Successfull subscription in company "
                    + company
                    + " with amount"
                    + amount
                    + "\n"
            );
        } else {
            this.fixedNotiArea.append("Error subscribing in company "
                    + company
                    + " with amount "
                    + amount
                    + "\n"
            );
        }
    }//GEN-LAST:event_getButtonMouseClicked

    private void companyFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_companyFocusGained
        // TODO add your handling code here:
        if (this.company.getText().equals("Amount")) {
            company.setText("");
        }
    }//GEN-LAST:event_companyFocusGained

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea auctionsListArea;
    private javax.swing.JScrollPane auctionsListPane;
    private javax.swing.JMenuItem close;
    private javax.swing.JTextField company;
    private javax.swing.JMenu file;
    private javax.swing.JTextArea fixedListArea;
    private javax.swing.JScrollPane fixedListPane;
    private javax.swing.JButton getButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JMenuBar menu;
    private javax.swing.JButton refresh;
    // End of variables declaration//GEN-END:variables
}
